<?php
    include ('templates/header.php');
    //Incluido o menu de navegação
?>
    <main>
     <!-- 
    Seu Codigo HTML VAI AQUI
    OBS não incluir as tags centrais do html, tais como, doctype, html, body, header, footer...
    Pois elas estão sendo inseridas atraves do header e footer...
    O bootstrap já está sendo carregado...
    Sugiro cada um criar seus templates em pastas diferentes...
    Elas estão localizadas em /autores/{name} ...
    Cada um terá seu css, para nao bagunçar as dos outros...
    No final colocaremos em um arquivo só...
    Os aquivos css de todos já foram criados e estão sendo carregados !Estão vazioos!...
    -->

    </main>

<?php
    include ('templates/footer.php');
    //Incluindo o rodapé
?>